export const one = require('./1.jpg')
export const two = require('./2.jpg')
export const three = require('./3.jpg')
export const four = require('./4.jpg')
export const five = require('./5.jpg')
export const six = require('./6.jpg')
export const seven = require('./7.jpg')
export const eight = require('./8.jpg')
